### ISSUE TITLE
您好，关于ob中使用quicker链接图片的问题，大佬看到麻烦回复一下  万分感谢！

### ISSUE THREAD

**Issue by SAKURAGI-1983** [1wingedangel/Profile-of-Gefenbauer#1]
老哥我想请教一下，我按步骤操作后Quicker插件弹出，正则匹配不成功，然后转换为aleksey-rezvov/obsidian-local-images，这个插件，应该是成功的了，显示路径已替换为本地，并且本地也有相应的文件，但是在ob界面只显示一个路径框 （"media\c49uqmdb34tfgq1n87e0.png" 未创建，点击以创建。）到这儿就不会了...简悦导出ob也尝试失败..三种方式前前后后搞了很多遍，从逻辑上讲还是老哥开发的插件好一些，涉及到本地迁移的情况也更为稳妥。您看您方便的话能不能稍微指导一下，万分感谢。 
V SAKURAGI-1983

**Comment by 1wingedangel** [comment]
你发到相关的Discussion里不要扔这里，另外也具体描述一下什么样的图片地址正则匹配不成功，Quicker上调试运行看一下哪个步骤出问题。
